

export const filenameLanguageMap: Record<string, string> = {
  '.babelrc': 'json',
  '.bash_login': 'shell',
  '.bash_profile': 'shell',
  '.bash_logout': 'shell',
  '.bashrc': 'shell',
  '.dockerignore': 'plaintext',
  '.editorconfig': 'ini',
  '.env': 'ini',
  '.envrc': 'shell',
  '.eslintrc': 'json',
  '.gitattributes': 'plaintext',
  '.gitconfig': 'ini',
  '.gitignore': 'plaintext',
  '.gitmodules': 'ini',
  '.npmrc': 'ini',
  '.prettierrc': 'json',
  '.profile': 'shell',
  '.zprofile': 'shell',
  '.zshenv': 'shell',
  '.zshrc': 'shell',
  'bun.lock': 'plaintext',
  'cargo.lock': 'ini',
  'dockerfile': 'dockerfile',
  'gemfile': 'ruby',
  'go.mod': 'go',
  'go.sum': 'plaintext',
  'makefile': 'shell',
  'package-lock.json': 'json',
  'podfile': 'ruby',
  'procfile': 'shell',
  'rakefile': 'ruby',
  'tsconfig.json': 'json',
  'vagrantfile': 'ruby',
  'yarn.lock': 'plaintext',
};

export const extensionLanguageMap: Record<string, string> = {
  abap: 'abap',
  apex: 'apex',
  azcli: 'azcli',
  bat: 'bat',
  bib: 'st',
  bicep: 'bicep',
  c: 'cpp',
  cc: 'cpp',
  cjs: 'javascript',
  clj: 'clojure',
  cljc: 'clojure',
  cljs: 'clojure',
  coffee: 'coffee',
  cpp: 'cpp',
  cs: 'csharp',
  cshtml: 'razor',
  csh: 'shell',
  css: 'css',
  cts: 'typescript',
  cu: 'cpp',
  cxx: 'cpp',
  dart: 'dart',
  dax: 'msdax',
  diff: 'plaintext',
  ecl: 'ecl',
  edn: 'clojure',
  eex: 'html',
  env: 'ini',
  ex: 'elixir',
  exs: 'elixir',
  fs: 'fsharp',
  fsi: 'fsharp',
  fsx: 'fsharp',
  gql: 'graphql',
  graphql: 'graphql',
  h: 'cpp',
  handlebars: 'handlebars',
  hbs: 'handlebars',
  hcl: 'hcl',
  hh: 'cpp',
  hlsl: 'cpp',
  hpp: 'cpp',
  hs: 'plaintext',
  html: 'html',
  htm: 'html',
  hxx: 'cpp',
  ini: 'ini',
  ipynb: 'json',
  java: 'java',
  jl: 'julia',
  js: 'javascript',
  json: 'json',
  json5: 'json',
  jsonc: 'json',
  jsx: 'javascript',
  kt: 'kotlin',
  kts: 'kotlin',
  less: 'less',
  liquid: 'liquid',
  lua: 'lua',
  m: 'objective-c',
  md: 'markdown',
  mdx: 'mdx',
  mjs: 'javascript',
  mm: 'objective-c',
  mts: 'typescript',
  mysql: 'mysql',
  patch: 'plaintext',
  php: 'php',
  phtml: 'php',
  pl: 'perl',
  pm: 'perl',
  ps1: 'powershell',
  psd1: 'powershell',
  psm1: 'powershell',
  pug: 'pug',
  py: 'python',
  pyw: 'python',
  r: 'r',
  rake: 'ruby',
  rb: 'ruby',
  redis: 'redis',
  rst: 'restructuredtext',
  rs: 'rust',
  sass: 'scss',
  sb: 'sb',
  sc: 'scala',
  scala: 'scala',
  scm: 'scheme',
  scss: 'scss',
  sh: 'shell',
  sol: 'solidity',
  sql: 'sql',
  svelte: 'html',
  swift: 'swift',
  systemverilog: 'systemverilog',
  tcl: 'tcl',
  tf: 'hcl',
  tfvars: 'hcl',
  toml: 'ini',
  ts: 'typescript',
  tsx: 'typescript',
  twig: 'twig',
  txt: 'plaintext',
  vb: 'vb',
  vue: 'html',
  wgsl: 'wgsl',
  xml: 'xml',
  yaml: 'yaml',
  yml: 'yaml',
  zsh: 'shell',
};

export const getLanguageFromPath = (filePath: string): string => {
  const fileName = filePath.split(/[\\/]/).pop() ?? filePath;
  const lowerName = fileName.toLowerCase();

  if (filenameLanguageMap[lowerName]) return filenameLanguageMap[lowerName];
  if (/^\.env(?:[.-].*)?$/.test(lowerName)) return 'ini';

  const ext = lowerName.includes('.') ? lowerName.split('.').pop() ?? '' : '';
  return extensionLanguageMap[ext] ?? 'plaintext';
};
